"""cascade delete note chunks

Revision ID: 290d8cb907fc
Revises: 65c9cb7e3590
Create Date: 2026-09-28 18:39:25.428115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '290d8cb907fc'
down_revision: Union[str, Sequence[str], None] = '65c9cb7e3590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('note_chunks_note_id_fkey'), 'note_chunks', type_='foreignkey')
    op.create_foreign_key('fk_note_chunk_note_id_notes', 'note_chunks', 'notes', ['note_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_note_chunk_note_id_notes', 'note_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('note_chunks_note_id_fkey'), 'note_chunks', 'notes', ['note_id'], ['id'])
    # ### end Alembic commands ###
