"""add subject to notes

Revision ID: b3b967bf2246
Revises: 551495dbc786
Create Date: 2026-09-22 13:08:08.795066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b967bf2246'
down_revision: Union[str, Sequence[str], None] = '551495dbc786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('subject', sa.String(length=100), nullable=True))

    op.execute(
        "UPDATE notes SET subject = 'Uncategorized' WHERE subject IS NULL"
    )

    op.alter_column(
        "notes",
        "subject",
        existing_type=sa.String(length=100),
        nullable=False
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'subject')
    # ### end Alembic commands ###
