"""add embeddings to note chunks

Revision ID: f2c21106faa1
Revises: 744072c26646
Create Date: 2026-09-28 19:36:07.566816

"""
from typing import Sequence, Union
from pgvector.sqlalchemy import Vector

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c21106faa1'
down_revision: Union[str, Sequence[str], None] = '744072c26646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "note_chunks",
        sa.Column(
            "embedding",
            Vector(384),
            nullable=True
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_chunks', 'embedding')
    # ### end Alembic commands ###
